commerce_payment.commerce_payment_gateway.plugin.commerce_payeezy_onsite_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    api_key:
      type: string
      label: 'API key'
    api_secret_key:
      type: string
      label: 'API secret'
    merchant_token:
      type: string
      label: 'Merchant token'
    transaction_url:
      type: string
      label: 'Transaction URL'
    js_security_key:
      type: string
      label: 'JS security key'
    ta_token:
      type: string
      label: 'TA token'
    callback:
      type: string
      label: 'Callback'
    token_type:
      type: string
      label: 'Token type'
    security_token_url:
      type: string
      label: 'Security token url'

commerce_payment.commerce_payment_gateway.plugin.commerce_payeezy_hosted_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    x_login:
      type: string
      label: 'Login'
    transaction_key:
      type: string
      label: 'Transaction key'
    x_response_key:
      type: string
      label: 'Response key'
    transaction_url:
      type: string
      label: 'Transaction URL'
    hmac_calculation:
      type: string
      label: 'HMAC Calculation'
